
|
| 68901 MFP Register Addresses
|

MFP = 0xf8000		| Base Address of MFP
MFP_GPDR = MFP+0x01	| General Purpose I/O Data Register
MFP_AER = MFP+0x03	| Active Edge Register
MFP_DDR = MFP+0x05	| Data Direction Register
MFP_IERA = MFP+0x07	| Interrupt Enable Register A
MFP_IERB = MFP+0x09	| Interrupt Enable Register B
MFP_IPRA = MFP+0x0b	| Interrupt Pending Register A
MFP_IPRB = MFP+0x0d	| Interrupt Pending Register B
MFP_ISRA = MFP+0x0f	| Interrupt In-service Register A
MFP_ISRB = MFP+0x11	| Interrupt In-service Register B
MFP_IMRA = MFP+0x13	| Interrupt Mask Register A
MFP_IMRB = MFP+0x15	| Interrupt Mask Register B
MFP_VR = MFP+0x17	| Vector Register
MFP_TACR = MFP+0x19	| Timer A Control Register
MFP_TBCR = MFP+0x1b	| Timer B Control Register
MFP_TCDCR = MFP+0x1d	| Timers C and D Control Register
MFP_TADR = MFP+0x1f	| Timer A Data Register
MFP_TBDR = MFP+0x21	| Timer B Data Register
MFP_TCDR = MFP+0x23	| Timer C Data Register
MFP_TDDR = MFP+0x25	| Timer D Data Register
MFP_SCR = MFP+0x27	| Synchronous Character Register
MFP_UCR = MFP+0x29	| USART Control Register
MFP_RSR = MFP+0x2b	| Receiver Status Register
MFP_TSR = MFP+0x2d	| Transmitter Status Register
MFP_UDR = MFP+0x2f	| USART Data Register

